---
version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest'

additional_build_files:
   - src: ../ansible.cfg
     dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  # append: |
  #   LABEL quay.expires-after="45d"
