---
collections:
  - name: servicenow.itsm
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.controller
  - name: awx.awx
  - name: amazon.cloud
  - name: community.aws
  - name: cloud.terraform
    version: 1.0.0
