---
collections:
  # ansible controller
  - name: ansible.controller
    version: 4.4.8
  - name: infra.controller_configuration
    version: 2.5.2
  # linux
  - name: ansible.posix
    version: 1.5.4
  - name: redhat.insights
    version: 1.2.2
  - name: redhat.rhel_system_roles
    version: 1.23.0
  - name: community.general
    version: 6.3.0
  - name: containers.podman
  # windows
  - name: chocolatey.chocolatey
  - name: community.windows
    version: 2.0.0
  - name: ansible.windows
    version: 1.13.0
  # cloud
  - name: azure.azcollection
    version: 1.14.0
  - name: amazon.aws
    version: 5.2.0
  # satellite
  - name: redhat.satellite
    version: 3.14.0
  # network
  - name: ansible.netcommon
    version: 5.3.0
